[build]
cmd = "go build -o ./tmp/main ./cmd/server"
bin = "./tmp/main"
exclude_dir = ["tmp", "vendor", "testdata"]  # Excluding unwanted dirs
include_dir = ["internal"]  # Including the internal directory and its subdirectories
include_ext = ["go", "tpl", "tmpl", "html"]  # You can also specify extensions if needed
log = "build-errors.log"
poll = false
stop_on_error = false

[color]
app = "cyan"
build = "yellow"
main = "magenta"
runner = "green"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = false

[proxy]
app_port = 0
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = false
keep_scroll = true